// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtI5E6LR71EHvMT2MDTv5ucAT9EU2Z_Uk',
    appId: '1:398797634163:web:b3d4c3f4c82159b182c806',
    messagingSenderId: '398797634163',
    projectId: 'rideshare-bdd66',
    authDomain: 'rideshare-bdd66.firebaseapp.com',
    storageBucket: 'rideshare-bdd66.firebasestorage.app',
    measurementId: 'G-F7ETYBW5DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH9Z4HlOBeo_aY2OYYqDvOxiGDLhi00bU',
    appId: '1:398797634163:android:5f6b3acd3903de9882c806',
    messagingSenderId: '398797634163',
    projectId: 'rideshare-bdd66',
    storageBucket: 'rideshare-bdd66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHPj8Vg-umTpyt10KPI_15Ld4hBHTKll0',
    appId: '1:398797634163:ios:783cd807668a2c6c82c806',
    messagingSenderId: '398797634163',
    projectId: 'rideshare-bdd66',
    storageBucket: 'rideshare-bdd66.firebasestorage.app',
    iosBundleId: 'com.example.rideShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHPj8Vg-umTpyt10KPI_15Ld4hBHTKll0',
    appId: '1:398797634163:ios:783cd807668a2c6c82c806',
    messagingSenderId: '398797634163',
    projectId: 'rideshare-bdd66',
    storageBucket: 'rideshare-bdd66.firebasestorage.app',
    iosBundleId: 'com.example.rideShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtI5E6LR71EHvMT2MDTv5ucAT9EU2Z_Uk',
    appId: '1:398797634163:web:6d4d853d268eacbb82c806',
    messagingSenderId: '398797634163',
    projectId: 'rideshare-bdd66',
    authDomain: 'rideshare-bdd66.firebaseapp.com',
    storageBucket: 'rideshare-bdd66.firebasestorage.app',
    measurementId: 'G-7MZ9TNTRL6',
  );
}
